name: genius_radio
description: Genius Radio

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  youtube_plyr_iframe:
    path: "./YoutubePlayerIFrame"
  flutter_neumorphic: ^3.0.4+1
  cupertino_icons: ^1.0.2
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  mobx_widget: ^0.4.2
  provider: ^4.1.3
  http: ^0.13.0
  google_fonts: ^2.0.0
  responsive_builder: ^0.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0

flutter:
  uses-material-design: true
